# Generated by Django 5.1.6 on 2025-02-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_admin_rename_role_student_role_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.role'),
        ),
    ]
